# SPDX-License-Identifier: GPL-2.0
# Isolated external-module build for the canonical CS8409 V10 source.
subdir-ccflags-y += -I$(src)/../common

snd-hda-codec-cs8409-y := cs8409.o cs8409-tables.o
obj-m += snd-hda-codec-cs8409.o
